'use client';
import {useEffect,useState,useCallback} from 'react';
import {Sparkles,Pause,Play} from 'lucide-react';
type Engine={enabled:boolean;approved:number;queries:{query:string;reason:string}[];recent:{id:string;query:string;status:string;message:string;created:string}[]};
export default function Autopilot(){
 const [data,setData]=useState<Engine|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/discover',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer)},[load]);
 async function toggle(){if(!data)return;setSaving(true);setError('');try{const r=await fetch('/api/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'configure',enabled:!data.enabled})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <section className="panel autopilot"><div className="panel-heading"><div><h3><Sparkles size={19}/>Motor automático</h3><p>Busca sozinho às 9h, 15h e 21h · Horário da Bahia · Funciona com a aba fechada</p></div><button className="btn outline small" disabled={!data||saving} onClick={()=>void toggle()}>{data?.enabled?<Pause size={15}/>:<Play size={15}/>} {saving?'Salvando…':data?.enabled?'Pausar':'Ativar'}</button></div>{error&&<p role="alert" className="feedback danger">{error}</p>}{data&&<><p><strong>{data.enabled?'Ativo':'Pausado'}</strong> · {data.approved} ofertas aprovadas. Cada rodada busca até 10 anúncios novos usando um dos temas abaixo. As aprovações e rejeições ajustam as próximas pesquisas.</p><div className="quick-tags">{data.queries.map(q=><span className="pill" key={q.query} title={q.reason}>{q.query}</span>)}</div>{!data.queries.length&&<p>Adicione palavras-chave ou aprove ofertas para orientar o motor.</p>}<small>Os temas são extraídos do texto das ofertas. Algumas rodadas usam suas palavras-chave para descobrir assuntos novos. Pausar impede as próximas rodadas; uma busca já iniciada termina normalmente.</small>{data.recent.length>0&&<details><summary>Últimas rodadas automáticas</summary>{data.recent.map(r=><div className="auto-run" key={r.id}><strong>{r.query} · {r.status}</strong><small>{new Date(r.created).toLocaleString('pt-BR',{timeZone:'America/Bahia'})}</small><p>{r.message||'Rodada iniciada. Aguardando resultado.'}</p></div>)}</details>}</>}</section>;
}
